name: Deploy JobCopilot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Contabo
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /opt/projects/jobcopilot

            if [ ! -d ".git" ]; then
              git clone https://github.com/ratsam93/jobcopilot.git .
            fi

            git pull origin main

            docker compose down || true
            docker compose up -d --build
